### ISSUE TITLE
Does this work with Next 11?

### ISSUE THREAD

**Issue by edgarasben** [blitz-js/babel-plugin-superjson-next#76] opened 2021-06-19 16:28 UTC
Seems like this stopped working for me when updated to Next 11.0.0.

Did anybody run into a similar issue?

```shell
error - ./pages/index.js
SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
```

**Comment by Skn0tt** [comment] 2021-06-21 09:16
Hi @edgarasben! I tried updating our example to Next 11 in #78, and it works fine both locally and in CI. Could you provide a minimal reproduction repo? That'd make it a lot easier for me to reproduce.

**Comment by tadeumaia** [comment] 2021-06-22 17:19
Same happening to me. 

There is not much to it, the page is just this with the appropriate config settings for babel.rc 

```
export const getServerSideProps: GetServerSideProps = async () => {
  const prisma = new PrismaClient()

  const users = await prisma.user.findMany()

  console.log(users)

  return {
    props: { users },
  }
}
```

**Comment by edgarasben** [comment] 2021-06-22 17:27
Exactly what @tadeumaia described. I can try to post a minimal reproduction repo later.

**Comment by Skn0tt** [comment] 2021-06-24 12:49
A repro would be great, thank you!

**Comment by thomaszdxsn** [comment] 2021-06-25 12:29
I have not work issue, but fixed by change `plugins: ["superjson-next"]` to `plugins: ["babel-plugin-superjson-next"]`

**Comment by Skn0tt** [comment] 2021-06-25 12:34
That sounds like a caching issue then. @edgarasben @tadeumaia have you tried deleting caches?

**Comment by edgarasben** [comment] 2021-06-26 09:16
> That sounds like a caching issue then. @edgarasben @tadeumaia have you tried deleting caches?

I am not an advanced developer, could you specify what do you mean by that in this case?

**Comment by gleuch** [comment] 2021-06-27 17:51
I was running into issues as well when upgrading to Next v11 where it would no longer catch `undefined` prop values from `getServerSideProps`. This worked without issue in 10.2.3.

We're running with Express server and defined the working directory when initializing NextJS (`const app = nextJS({ dir: './src' });`).

When we removed `dir` parameter (`src/pages` is supported by default in Next), this resolved our issue with SuperJSON not running.

Not entirely sure if that is helpful, but could be a starting point to look at issues with custom directories?

**Comment by Skn0tt** [comment] 2021-07-02 08:08
> could you specify what do you mean by that in this case?

Sure! Babel plugins such as `babel-plugin-superjson-next` transpile your code. For efficiency, they try to *cache* their work: If a piece of code has been transpiled once, it won't be transpiled again. Sometimes this means stale caches: Something changed so you'd want everything to be re-transpiled again, but it doesn't since it's cached. Deleting caches is the easiest way to work around this.

For Next applications, deleting the `.next` folder should be the easiest way to delete caches.

>  but could be a starting point to look at issues with custom directories?

A reproduction repository would be a great starting point.

**Comment by knaitas** [comment] 2021-07-11 11:16
Had the same issue and can confirm that deleting `.next` folder a.k.a cleaning the cache helps to solve this :)

**Comment by Skn0tt** [comment] 2021-07-26 07:09
Closing this, as it seems to be fixed by purging the cache :)

**Closed by Skn0tt** 2021-07-26 07:09 UTC
Labels: bug

**Comment by edgarasben** [comment] 2021-07-26 19:02
@Skn0tt sorry for the late reply. When it did not work I removed the script from my codebase. But most likely you are right. It's the old .next cache that might have caused the problem. I will try using the script in the future and report here again, in case the problems persist.
